package com.epicdima.lib.dal.utils;

import com.epicdima.lib.dal.executors.SqlExecutorWithReturnedValue;
import com.epicdima.lib.dal.other.ConnectionPool;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Optional;

/**
 * @author EpicDima
 */
public final class JdbcUtils {

    private JdbcUtils() {
        throw new AssertionError();
    }

    public static PreparedStatement prepareStatement(Connection connection, String query)
            throws SQLException {
        return connection.prepareStatement(query);
    }

    public static PreparedStatement prepareStatement(Connection connection, String query, int autoGeneratedKeys)
            throws SQLException {
        return connection.prepareStatement(query, autoGeneratedKeys);
    }

    public static <T> T execute(ConnectionPool connectionPool,
                                SqlExecutorWithReturnedValue<T> executor) {
        Connection connection = connectionPool.getConnection();
        try {
            return executor.execute(connection);
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        } finally {
            connectionPool.releaseConnection(connection);
        }
    }
}
